alias l='eza -l'
alias ls='eza'
alias ll='eza -la'
alias li='eza -l --icons'
alias tree='eza --tree'

alias k='kubectl'
alias ksys='kubectl -n kube-system'
alias klogs='kubectl logs'
alias ksyslogs='kubectl -n kube-system logs'
alias kexec='kubectl exec -it'
alias ksysexec='kubectl -n kube-system exec -it'
alias kpods='kubectl get pods -o wide'
alias ksyspods='kubectl -n kube-system get pods -o wide'
