# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export LANG=en_US.UTF-8
export EDITOR='hx'
export PAGER="less -FirSwX"

# Remove zsh default shell warnings on macos
export BASH_SILENCE_DEPRECATION_WARNING=1

# Setting termifo in bashrc as I don't rely on terminal specific features anyways.
export TERM=xterm-256color

shopt -s histappend
shopt -s checkwinsize

export HISTCONTROL=ignoredups:erasedups
export HISTFILESIZE=
export HISTSIZE=

# Remove zsh default shell warningin on macos
export BASH_SILENCE_DEPRECATION_WARNING=1

case "$(uname -s)" in
  Darwin*) export PATH="${PATH}:/opt/homebrew/bin/:/opt/homebrew/sbin/";;
esac
export PATH="${PATH}:${HOME}/.local/bin"

## Shell aliases

alias sbash='source ~/.bashrc'

alias l='ls -la --color=auto'
alias ls='ls --color=auto'

alias gs="git status"
alias gl="git log --oneline --graph --abbrev-commit --decorate"

## Helpful shell tooling

if command -v zoxide &> /dev/null; then
  eval "$(zoxide init bash)"
fi

if command -v fzf &> /dev/null; then
  eval "$(fzf --bash)"
fi

## Configure bash prompt.

export TERM_COLOR_NONE="\033[00m"
export TERM_COLOR_BLUE="\033[0;34m"
export TERM_COLOR_GREEN="\033[0;32m"
export TERM_COLOR_YELLOW="\033[0;33m"
export TERM_COLOR_RED="\033[0;31m"
export TERM_COLOR_CYAN="\033[0;36m"

function print_git_branch() {
    echo -e "${TERM_COLOR_BLUE}$(git branch 2> /dev/null | sed -e '/^[^*]/d' | sed -e 's/* \(.*\)/( \1)/')${TERM_COLOR_NONE}"
}

function print_shell_indidcator() {
  INDICATOR_COLOR="${TERM_COLOR_BLUE}"
  if [ $? -eq 0 ]; then
    INDICATOR_COLOR="${TERM_COLOR_RED}"
  fi
  echo -e "${INDICATOR_COLOR}\$${TERM_COLOR_NONE}"
}

function print_cwd() {
  echo -e "${TERM_COLOR_YELLOW}$(dirs +0)${TERM_COLOR_NONE}"
}

function print_main_prompt() {
  HOST_INFO=""
  if ! [ -z "${PROMPT_VERBOSE}" ]; then
    HOST_INFO="${TERM_COLOR_CYAN}@${HOSTNAME}${TERM_COLOR_NONE}"
  fi
  echo -e "${TERM_COLOR_BLUE}[${TERM_COLOR_GREEN}${USER}${HOST_INFO}${TERM_COLOR_BLUE}]${TERM_COLOR_NONE}"
}

# To enable hostname in prompt: export PROMPT_VERBOSE=1
export PROMPT_VERBOSE=${PROMPT_VERBOSE:-1}

PS1="\$(print_main_prompt) \$(print_shell_indidcator) \$(print_cwd) \$(print_git_branch)"
PS1+="\n${BLUE_COLOR}ᗆ ${NO_COLOR}"
