# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export LANG=en_US.UTF-8
export EDITOR='nvim'
export PAGER="less -FirSwX"

# Required for nushell on macos
export XDG_CONFIG_HOME=~/.config

# Remove zsh default shell warnings on macos
export BASH_SILENCE_DEPRECATION_WARNING=1

# Setting termifo in bashrc as I don't rely on terminal specific features anyways.
export TERM=xterm-256color

shopt -s histappend
shopt -s checkwinsize

export HISTCONTROL=ignoredups:erasedups
export HISTFILESIZE=
export HISTSIZE=

# Remove zsh default shell warningin on macos
export BASH_SILENCE_DEPRECATION_WARNING=1

PROMPT_ICON=""
case "$(uname -s)" in
  Darwin*) export PATH="${PATH}:/opt/homebrew/bin/:/opt/homebrew/sbin/"; PROMPT_ICON="";;
esac
export PATH="${PATH}:${HOME}/.local/bin"

## Shell aliases and tooling.

alias sbash='source ~/.bashrc'

if command -v eza &> /dev/null; then
  alias l='eza -l'
  alias ls='eza'
  alias ll='eza -la'
  alias li='eza -l --icons'
  alias tree='eza --tree'
else
  alias l='ls -l --color=auto'
  alias ll='ls -la --color=auto'
  alias ls='ls --color=auto'
fi

alias gs="git status"
alias gl="git log --oneline --graph --abbrev-commit --decorate"

alias nmux="SHELL=$(which nu) tmux -L nu-server $@"
alias note="nu --config ~/.config/nushell/env.nu -c note"

if command -v zoxide &> /dev/null; then
  eval "$(zoxide init --cmd cd bash)"
fi

if command -v fzf &> /dev/null; then
  eval "$(fzf --bash)"
  if command -v fd &> /dev/null; then
	# Set fd as the default source for fzf (respects .gitignore, includes hidden files)
	export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'
	export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
	export FZF_ALT_C_COMMAND='fd --type d --strip-cwd-prefix --hidden --follow --exclude .git'

	export FZF_DEFAULT_OPTS="--layout=reverse"
  fi
fi

if command -v go &> /dev/null; then
  export PATH="${PATH}:${HOME}/go/bin"
fi

if command -v cargo &> /dev/null; then
  export PATH="${PATH}:${HOME}/.cargo/bin"
fi

if command -v kubectl &> /dev/null; then
  alias k='kubectl'
  alias ksys='kubectl -n kube-system'
  alias klogs='kubectl logs'
  alias ksyslogs='kubectl -n kube-system logs'
  alias kexec='kubectl exec -it'
  alias ksysexec='kubectl -n kube-system exec -it'
  alias kpods='kubectl get pods -o wide'
  alias ksyspods='kubectl -n kube-system get pods -o wide'
fi

## Configure bash prompt.

export TERM_COLOR_NONE="\033[00m"
export TERM_COLOR_RED="\033[0;31m"
export TERM_COLOR_GREEN="\033[0;32m"
export TERM_COLOR_YELLOW="\033[0;33m"
export TERM_COLOR_BLUE="\033[0;34m"
export TERM_COLOR_MAGENTA="\033[0;35m"
export TERM_COLOR_CYAN="\033[0;36m"

function print_git_branch() {
    echo -e "${TERM_COLOR_BLUE}$(git branch 2> /dev/null | sed -e '/^[^*]/d' | sed -e 's/* \(.*\)/( \1)/')${TERM_COLOR_NONE}"
}

function print_shell_indidcator() {
  INDICATOR_COLOR="${TERM_COLOR_RED}"
  if [ $? -eq 0 ]; then
    INDICATOR_COLOR="${TERM_COLOR_BLUE}"
  fi
  echo -e "${INDICATOR_COLOR}\$${TERM_COLOR_NONE}"
}

function print_cwd() {
  echo -e "${TERM_COLOR_YELLOW}$(dirs +0)${TERM_COLOR_NONE}"
}

function print_main_prompt() {
  HOST_INFO=""
  if ! [ -z "${PROMPT_VERBOSE}" ]; then
    HOST_INFO="${TERM_COLOR_CYAN}@${HOSTNAME}${TERM_COLOR_NONE}"
  fi
  echo -e "${TERM_COLOR_BLUE}[${TERM_COLOR_GREEN}${USER}${HOST_INFO} ${TERM_COLOR_MAGENTA}${PROMPT_ICON}${TERM_COLOR_BLUE}]${TERM_COLOR_NONE}"
}

function print_prompt_indicator() {
  echo -e "${TERM_COLOR_BLUE}ᗆ ${TERM_COLOR_NONE}"
}

# To enable hostname in prompt: export PROMPT_VERBOSE=1
# export PROMPT_VERBOSE=${PROMPT_VERBOSE:-1}

PS1="\$(print_main_prompt) \$(print_shell_indidcator) \$(print_cwd) \$(print_git_branch)"
# New line prompt indicator with color breaks the shell.
# PS1+="\n\$(print_prompt_indicator)"
PS1+="\nᗆ "
